---
title: "Plan du cours"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# Chapitre 1 :
Le système monétaire international (S.M.I) et notions fondamentales en finance internationale

Section 1 : aperçu historique 

Section 2 : le fonctionnement de marché de change

Section 3 : les participants sur le marché de change 

Section 4 : les opérations sur le marché de change

Section 5 : le marché de change tunisien

# Chapitre 2 : 
Les caractéristiques générales du marché de change

 Section 1 : le marché de change au comptant (SPOT)
 
 Section 2 : le marché de change à terme (FORWRD)

# Chapitre 3 : 
Le marché des Eurodevises

Section 1 : Les cotations sur le marché des eurodevises

Section 2 : Les mécanismes de formation des cours à terme  

Section 3 : Les parités internationales
 
# Chapitre 4 : 
Le risque de change et sa couverture 

  Section 1 : Techniques de couverture faisant appel au marché spécialisé ( contrats « FUTURE ») 
  
  Section 2 : Techniques de couverture par les options 





